version: "2.21"
services:
  main:
      image: plantidbot
      build: .
      container_name: plantidbot
      restart: unless-stopped
      environment:
        - DISCORD_TOKEN
        - PLANTNET_API_KEY
