name: Production Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      PLANTNET_API_KEY: ${{ secrets.PLANTNET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into Server and run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/ffe-scraper
            ls -la
            git pull
            docker compose down
            docker compose up --build -d
